news_title_blacklist = [
    "*TOP NEWS*",
    "Earnings Call",
    "10-Q",
    "10-K",
    "DEF 14A",
    "of the week",
    "PREM14A",
    "Transcript",
    "A roundup of",
    "(Webcast)",
    "24/7",
    "SERVICE ALERT",
    "Morning News Call",
    "new issue index",
    "Swiss stocks",
    "index pages",
    "End of Day Market",
    "list of hedge funds",
    "*Reuters Breakingviews*",
    "NHL results",
    "NBA results",
    "SHH Margin Trading",
    "championship results",
    "UPDATE 2-Soccer",
    "UPDATE 1-Soccer",
    "Soccer-Ligue",
    "results and standings",
    "Soccer-",
    "NBA standings",
    "pls ignore",
    "8-K/A",
    "Premarket gainers",
    "Premarket losers",
    "postmarket earnings",
    "Pre-market gainers",
    "Notable earnings",
    "NBA-Highlights",
    "Reuters Sports",
    "NHL",
    "Morning Call-Global Markets",
    "PRESS DIGEST-",
    "CBOT",
    "NFL-",
    "Stocks to Watch",
    "After-Hours Earnings",
    "BOJ o/n call",
    "BOJ offers",
    "BOJ:",
    "DIARY-",
    "parent forecast",
    "group forecast",
    "Cricket-",
    "TABLE-",
    "summary",
    "Subscribe to the FT to read",
    "India Port Conditions",
    "Block Dea",
    "Factors to Watch",
    "Daily Earnings",
    "PMI",
    "index",
    "weekly export sales",
    "FX Markets Open",
    "gainers",
    "New Issue",
    "BRIEF-",
    "Today:",
    "TAKE A LOOK-",
    "highlights",
    "Highlights",
    "DIARY -",
    "Reuters Insider",
    "INTERVIEW-",
    "BUZZ-",
    "PRESS DIGEST",
    "P: $",
    "- Slideshow",
]

news_content_blacklist = [
    "Seeking Alpha PRO Marketplace",
    "On The Move",
    'Please click "I am not a robot"',
    "To access the newsletter",
    "Latest analyst recommendations",
    "Today:",
    "Tenor Offer Tendered Awarded",
]

skipped_entity_types = [
    # "Category:Stock_exchanges",
    # "Category:Electronic_trading_platforms",
    # "Category:Newspapers",
    # "Category:Television_terminology",
    # "newspapers",
    # "television_channel",
    # "news_channel",
    # "Category:Days_of_the_week",
    # "Category:Units_of_",
    # "Category:Months",
    # "Category:Time",
    # "Category:Days_of_the_year",
    "_news_"
]

ignored_entity_type = [
    "CARDINAL",
    "LANG",
    "LANGUAGE",
    "MONEY",
    "ORDINAL",
    "PERCENT",
    "QUANTITY",
    "TIME",
    "DATE",
]

skipped_relationships = [
    "http://www.w3.org/2000/01/rdf-schema#seeAlso",
    "http://dbpedia.org/ontology/timeZone",
    "http://www.w3.org/2002/07/owl#differentFrom",
    "http://dbpedia.org/ontology/languageFamily",
    "http://dbpedia.org/ontology/language",
    "http://dbpedia.org/ontology/populationPlace",
    "http://dbpedia.org/ontology/wikiPageDisambiguates",
    "http://dbpedia.org/ontology/wikiPageRedirects",
    "http://dbpedia.org/property/label",
    "http://dbpedia.org/property/timeZoneDst",
    "http://dbpedia.org/property/cctld",
]

abstraction_relationships = [
    "http://www.w3.org/1999/02/22-rdf-syntax-ns#type",
    "http://purl.org/dc/terms/subject",
    "http://dbpedia.org/ontology/class",
    "http://purl.org/linguistics/gold/hypernym",
    "http://dbpedia.org/ontology/industry",
    "http://dbpedia.org/property/industry",
    "http://dbpedia.org/ontology/type",
]
# skipped_verbs = "say announce make let report reported said discuss appear reveal look reporters see will expect push may clarify ask come mandate seek see want"
pronouns = "all another any anybody anyone anything as aught both each each other either enough everybody everyone everything few he her hers herself him himself his I idem it its itself many me mine most my myself naught neither no one nobody none nothing nought one one another other others ought our ours ourself ourselves several she some somebody someone something somewhat such suchlike that thee their theirs theirself theirselves them themself themselves there these they thine this those thou thy thyself us we what whatever whatnot whatsoever whence where whereby wherefrom wherein whereinto whereof whereon wherever wheresoever whereto whereunto wherewith wherewithal whether which whichever whichsoever who whoever whom whomever whomso whomsoever whose whosever whosesoever whoso whosoever ye yon yonder you your yours yourself yourselves"


ENGLISH_STOP_WORDS = frozenset(
    [
        "a",
        "about",
        "above",
        "across",
        "after",
        "afterwards",
        "again",
        "against",
        "all",
        "almost",
        "alone",
        "along",
        "already",
        "also",
        "although",
        "always",
        "am",
        "among",
        "amongst",
        "amoungst",
        "amount",
        "an",
        "and",
        "another",
        "any",
        "anyhow",
        "anyone",
        "anything",
        "anyway",
        "anywhere",
        "are",
        "around",
        "as",
        "at",
        "back",
        "be",
        "became",
        "because",
        "become",
        "becomes",
        "becoming",
        "been",
        "before",
        "beforehand",
        "behind",
        "being",
        "below",
        "beside",
        "besides",
        "between",
        "beyond",
        "bill",
        "both",
        "bottom",
        "but",
        "by",
        "call",
        "can",
        "cannot",
        "cant",
        "co",
        "con",
        "could",
        "couldnt",
        "cry",
        "de",
        "describe",
        "detail",
        "do",
        "done",
        "down",
        "due",
        "during",
        "each",
        "eg",
        "eight",
        "either",
        "eleven",
        "else",
        "elsewhere",
        "empty",
        "enough",
        "etc",
        "even",
        "ever",
        "every",
        "everyone",
        "everything",
        "everywhere",
        "except",
        "few",
        "fifteen",
        "fifty",
        "fill",
        "find",
        "fire",
        "first",
        "five",
        "for",
        "former",
        "formerly",
        "forty",
        "found",
        "four",
        "from",
        "front",
        "full",
        "further",
        "get",
        "give",
        "go",
        "had",
        "has",
        "hasnt",
        "have",
        "he",
        "hence",
        "her",
        "here",
        "hereafter",
        "hereby",
        "herein",
        "hereupon",
        "hers",
        "herself",
        "him",
        "himself",
        "his",
        "how",
        "however",
        "hundred",
        "i",
        "ie",
        "if",
        "in",
        "inc",
        "indeed",
        "interest",
        "into",
        "is",
        "it",
        "its",
        "itself",
        "keep",
        "last",
        "latter",
        "latterly",
        "least",
        "less",
        "ltd",
        "made",
        "many",
        "may",
        "me",
        "meanwhile",
        "might",
        "mill",
        "mine",
        "more",
        "moreover",
        "most",
        "mostly",
        "move",
        "much",
        "must",
        "my",
        "myself",
        "name",
        "namely",
        "neither",
        "never",
        "nevertheless",
        "next",
        "nine",
        "no",
        "nobody",
        "none",
        "noone",
        "nor",
        "not",
        "nothing",
        "now",
        "nowhere",
        "of",
        "off",
        "often",
        "on",
        "once",
        "one",
        "only",
        "onto",
        "or",
        "other",
        "others",
        "otherwise",
        "our",
        "ours",
        "ourselves",
        "out",
        "over",
        "own",
        "part",
        "per",
        "perhaps",
        "please",
        "put",
        "rather",
        "re",
        "same",
        "see",
        "seem",
        "seemed",
        "seeming",
        "seems",
        "serious",
        "several",
        "she",
        "should",
        "show",
        "side",
        "since",
        "sincere",
        "six",
        "sixty",
        "so",
        "some",
        "somehow",
        "someone",
        "something",
        "sometime",
        "sometimes",
        "somewhere",
        "still",
        "such",
        "system",
        "take",
        "ten",
        "than",
        "that",
        "the",
        "their",
        "them",
        "themselves",
        "then",
        "thence",
        "there",
        "thereafter",
        "thereby",
        "therefore",
        "therein",
        "thereupon",
        "these",
        "they",
        "thick",
        "thin",
        "third",
        "this",
        "those",
        "though",
        "three",
        "through",
        "throughout",
        "thru",
        "thus",
        "to",
        "together",
        "too",
        "top",
        "toward",
        "towards",
        "twelve",
        "twenty",
        "two",
        "un",
        "under",
        "until",
        "up",
        "upon",
        "us",
        "very",
        "via",
        "was",
        "we",
        "well",
        "were",
        "what",
        "whatever",
        "when",
        "whence",
        "whenever",
        "where",
        "whereafter",
        "whereas",
        "whereby",
        "wherein",
        "whereupon",
        "wherever",
        "whether",
        "which",
        "while",
        "whither",
        "who",
        "whoever",
        "whole",
        "whom",
        "whose",
        "why",
        "will",
        "with",
        "within",
        "without",
        "would",
        "yet",
        "you",
        "your",
        "yours",
        "yourself",
        "yourselves",
    ]
)
